// Objective-C API for talking to github.com/peterSZW/ebdemo/mobile Go package.
//   gobind -lang=objc github.com/peterSZW/ebdemo/mobile
//
// File is generated by gobind. Do not edit.

#ifndef __Mobile_H__
#define __Mobile_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


FOUNDATION_EXPORT void MobileDummy(void);

#endif
